trigger:
  branches:
    include:
      - develop

variables:
  - group: tpfinal-vars

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
      - job: BuildFrontend
        steps:
          - checkout: self

          - template: templates/_build-front.yml

